stages:
  - make
  - post

default:
  stage: make
  script:
    - python3 -m sphinx.cmd.build docs/source docs/build -b html

pages:
  stage: post
  script:
    - mv docs/build/html public
  artifacts:
    paths:
      - public
  only:
    - master