pages:
  before_script:
    - apt-get -qq update && apt-get -qq install -y python3
    - apt-get -qq update
    - apt-get -qq install -y python3 python3-virtualenv python3-pip
    - python3 -m virtualenv venv
    - . venv/bin/activate
    - python3 -V
    - python3 -m pip install sphinx
    - python3 -m pip install pygame
  script:
    - python3 -m sphinx.cmd.build docs/source docs/build -b html
    - mv docs/build public
  artifacts:
    paths:
      - public
  only:
    - master
