stages:
  - make
  - post

default:
  stage: make
  before_script:
    - apt-get -qq update && apt-get -qq install -y python3
    - apt-get -qq update
    - apt-get -qq install -y python3 python3-virtualenv python3-pip
    - virtualenv venv
    - . venv/bin/activate
    - python3 -V
    - python3 -m pip install sphinx
  script:
    - python3 -m sphinx.cmd.build docs/source docs/build -b html

pages:
  stage: post
  script:
    - mv docs/build/html public
  artifacts:
    paths:
      - public
  only:
    - master