stages:
  - make
  - post

windows job:
  stage: make
  script:
    - chmod +x docs/make.bat html

pages:
  stage: post
  script:
    - mv docs/build/html public
  artifacts:
    paths:
      - public
  only:
    - master